/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cafetera;
import javax.swing.JOptionPane;

/**
 *
 * @author pared
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Cafetera c;
    public Principal() {
        initComponents();
        cmbAgregarCafe.setEnabled(false);
        cmbVaciarCafe.setEnabled(false);
        cmbServirTaza.setEnabled(false);
        cmbPrenderCafetera.setEnabled(true);
        cmbLlenarCafetera.setEnabled(false);
        cmbApagar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbPrenderCafetera = new javax.swing.JButton();
        cmbServirTaza = new javax.swing.JButton();
        cmbVaciarCafe = new javax.swing.JButton();
        cmbAgregarCafe = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidadActual = new javax.swing.JTextField();
        txtCapacidadMaxima = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCantidadTaza = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCafeAgregar = new javax.swing.JTextField();
        cmbLlenarCafetera = new javax.swing.JButton();
        cmbApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cafetera");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        cmbPrenderCafetera.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbPrenderCafetera.setText("Prender Cafetera");
        cmbPrenderCafetera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPrenderCafeteraActionPerformed(evt);
            }
        });
        jPanel1.add(cmbPrenderCafetera, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 150, -1));

        cmbServirTaza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbServirTaza.setText("Servir Taza");
        cmbServirTaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbServirTazaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbServirTaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 150, -1));

        cmbVaciarCafe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbVaciarCafe.setText("Vaciar Cafe");
        cmbVaciarCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVaciarCafeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbVaciarCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 150, -1));

        cmbAgregarCafe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbAgregarCafe.setText("Agregar Cafe");
        cmbAgregarCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAgregarCafeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAgregarCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 150, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cafetera", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cantidad Maxima:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad Actual:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtCantidadActual.setEditable(false);
        jPanel2.add(txtCantidadActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 100, -1));

        txtCapacidadMaxima.setEditable(false);
        jPanel2.add(txtCapacidadMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 290, 110));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Op Cafetera", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad Taza:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));

        txtCantidadTaza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadTazaKeyTyped(evt);
            }
        });
        jPanel3.add(txtCantidadTaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cafe a Agregar:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtCafeAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCafeAgregarKeyTyped(evt);
            }
        });
        jPanel3.add(txtCafeAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, 120));

        cmbLlenarCafetera.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbLlenarCafetera.setText("Llenar Cafetera");
        cmbLlenarCafetera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLlenarCafeteraActionPerformed(evt);
            }
        });
        jPanel1.add(cmbLlenarCafetera, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 150, -1));

        cmbApagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbApagar.setText("Apagar Cafetera");
        cmbApagar.setToolTipText("");
        cmbApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbApagarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 610, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPrenderCafeteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPrenderCafeteraActionPerformed
        // TODO add your handling code here:
        c = new Cafetera ();
        
        txtCapacidadMaxima.setText(""+c.getCapacidad_Maxima());
        txtCantidadActual.setText(""+c.getCantidad_Actual());
        
        cmbAgregarCafe.setEnabled(false);
        cmbLlenarCafetera.setEnabled(true);
        cmbPrenderCafetera.setEnabled(false);
        cmbServirTaza.setEnabled(false);
        cmbVaciarCafe.setEnabled(false);
        cmbApagar.setEnabled(true);
    }//GEN-LAST:event_cmbPrenderCafeteraActionPerformed

    private void cmbServirTazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbServirTazaActionPerformed
        // TODO add your handling code here
        int taza;
        if (txtCantidadTaza.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese la cantidad a servir", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else 
        {
        taza= Integer.parseInt(txtCantidadTaza.getText());
        
        c.ServirTaza(taza);
        
        txtCantidadActual.setText(""+c.getCantidad_Actual());
        
        txtCantidadTaza.setText("");
        }
    }//GEN-LAST:event_cmbServirTazaActionPerformed

    private void cmbLlenarCafeteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLlenarCafeteraActionPerformed
        // TODO add your handling code here:
        int llenarcafetera;
        
        llenarcafetera = c.getCantidad_Actual();
        c.LlenarCafetera(llenarcafetera);
        
        txtCantidadActual.setText(""+c.getCantidad_Actual());
       
        txtCantidadTaza.setText("");
        txtCafeAgregar.setText("");
        
        cmbAgregarCafe.setEnabled(true);
        cmbApagar.setEnabled(true);
        cmbLlenarCafetera.setEnabled(true);
        cmbPrenderCafetera.setEnabled(false);
        cmbServirTaza.setEnabled(true);
        cmbVaciarCafe.setEnabled(true);
    }//GEN-LAST:event_cmbLlenarCafeteraActionPerformed

    private void cmbVaciarCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVaciarCafeActionPerformed
        // TODO add your handling code here:
        int vaciarcaf=0;
        txtCantidadActual.setText(""+ vaciarcaf);
        
    }//GEN-LAST:event_cmbVaciarCafeActionPerformed

    private void cmbAgregarCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAgregarCafeActionPerformed
        // TODO add your handling code here:
        int agregarcafe;
        if (txtCafeAgregar.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese la cantidad a Agregar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else {
            
        agregarcafe= Integer.parseInt(txtCafeAgregar.getText());
        if (c.getCantidad_Actual()<agregarcafe)
        {
            JOptionPane.showMessageDialog(this, "Supera la capacidad maxima de la Cafetera", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else {
        c.AgregarCafe(agregarcafe);
        txtCantidadActual.setText(""+c.getCantidad_Actual());
        txtCafeAgregar.setText("");
        }
        }
        
    }//GEN-LAST:event_cmbAgregarCafeActionPerformed

    private void cmbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbApagarActionPerformed
        // TODO add your handling code here:
        txtCafeAgregar.setText("");
        txtCantidadActual.setText("");
        txtCantidadTaza.setText("");
        txtCapacidadMaxima.setText("");
        
        cmbAgregarCafe.setEnabled(false);
        cmbApagar.setEnabled(false);
        cmbLlenarCafetera.setEnabled(false);
        cmbPrenderCafetera.setEnabled(true);
        cmbServirTaza.setEnabled(false);
        cmbVaciarCafe.setEnabled(false);
    }//GEN-LAST:event_cmbApagarActionPerformed

    private void txtCantidadTazaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadTazaKeyTyped
        // TODO add your handling code here:
         char d = evt.getKeyChar();
        if (!Character.isDigit(d)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadTazaKeyTyped

    private void txtCafeAgregarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCafeAgregarKeyTyped
        // TODO add your handling code here:
        char d = evt.getKeyChar();
        if (!Character.isDigit(d)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCafeAgregarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbAgregarCafe;
    private javax.swing.JButton cmbApagar;
    private javax.swing.JButton cmbLlenarCafetera;
    private javax.swing.JButton cmbPrenderCafetera;
    private javax.swing.JButton cmbServirTaza;
    private javax.swing.JButton cmbVaciarCafe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCafeAgregar;
    private javax.swing.JTextField txtCantidadActual;
    private javax.swing.JTextField txtCantidadTaza;
    private javax.swing.JTextField txtCapacidadMaxima;
    // End of variables declaration//GEN-END:variables
}
